spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/tj_remark?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    host: localhost
    database: 0
  rabbitmq:
    host: 192.168.112.102
    port: 5672
    username: itheima
    password: 123321
    publisher-confirm-type: correlated  # 开启发布确认，可选 none（关闭）、correlated（异步回调）、simple（同步等待确认）
    publisher-returns: true  # 开启发布返回
  application:
    name: remark-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.28:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8003